language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
node_js:
  - "stable"
install:
  - npm install
jobs:
  include:
    # - stage: test
    #   script: ember test
    - stage: build
      script: npm run build
    - stage: "deploy GH-PAGES"
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: build
        on:
          branch: master
    - stage: "deploy heroku"
      deploy: &heroku
        provider: heroku
        api_key:
          secure: Yd1qpjFJ/mXDaqUIQLDkt40+S2YKuitiQJzdECjFT6QMFPEUw29Zf/49yasjkPRIqKM1jCmGDkSQ4v8KfmHZFmB+vQg6AZZIHClcGfTNxrWH9F7nJpihc0VB0pxiFRAXzEELRKjfB1/eFAhVdwmMAx0AZmkoKmM+3BX4TIvHReEGGkEyQR0QfyRI7Skcs7bAPuwLX4aEAwKejDl3Puhrlu8krlNRgNxf04OUwvQ34S20OZeV1KmmqhNn3VXrQwrUgplNJ/uk1zmG0K/sDBz5Q6fT42pHhZ8j2zWjBoTOzU6NphTqZaMOO9LYNfpqRvyNyPpcsnpg9rpgJbMrgyf9PpHKew89Md2SCgkWdyHwXaWqjExkP6UxImszV6ndewILnSoCTDj/ZJUHHuLLw9kvR8cekHwi8xR2zFLLrD/RydzIgB95mtboxcKnBzNWAaKq8Qr0YvvlIvhU2Ef/rsDShXd6zTRZE+vCHK384/nO+GfDbVaRCjKDfRRe+mim25wAPFpSdm9uvZhLOJf3gpUhVvOEi3I1F44H/+wT3luXyR3RWPGG+faGLFBLq1AlFjqruckVut8tmGS0u4BNZ1fq4ecobwjttwPmNF3VFlzHfRWaOPBRaGe6MV+EsBVY9hmjmw8lZJgdGfRz0x3Vrv/Sn/dxrvS9hrE0UFiWnUjAAT0=
        app: react-marvel-app
        on:
          repo: kappys1/react-marvel-comics

after_success:
  # - npm run travis-deploy-once "npm run report-coverage"
  # - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  #   run travis-deploy-once "npm run deploy-gh"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
    run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
